apiVersion: v1
kind: Service
metadata:
  name: ms-java-camunda-service
  namespace: default
  labels:
    app: ms-java-camunda
spec:
  type: ClusterIP
  selector:
    app: ms-java-camunda
  ports:
    - name: ms-java-camunda-service
      port: 8087
      targetPort: 8087
  sessionAffinity: ClientIP
